version: 2

sphinx:
  configuration: docs/conf.py

formats: all

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    post_install:
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs
